### ISSUE TITLE
Normalize Transform should cater for channel >1

### ISSUE THREAD

**Issue by jerofad** [raghavian/loTeNet_pytorch#1]
A quick look at the code shows if you have your `--nChannel > 1`, then this line would throw an error `trans_valid = transforms.Compose([transforms.Normalize(mean=[0.5],std=[0.5])])`  because its only expecting 1 channel and not 3. 
I'm I missing something?

**Comment by raghavian** [comment]
Thanks for raising the issue. Fix is in this [commit.](https://github.com/raghavian/loTeNet_pytorch/commit/7becf15b430512dab7ac940f66ee6aefaa8140d4)
