### ISSUE TITLE
What is the meaning of the parameter "kScale" in LoTeNet?

### ISSUE THREAD

**Issue by timqqt** [raghavian/loTeNet_pytorch#2]
self.kScale = 4

Why you preset it to 4? What is the meaning of this?

Thanks!

**Comment by raghavian** [comment]
It is the kernel stride for the first squeeze operation. This is performed to increase the local feature map dimension at input. This can also be set to self.ker so that all layers end up having the same extent of squeezing.

**Comment by timqqt** [comment]
Thanks!
