### ISSUE TITLE
Hello, I'd like to ask you some questions about the datasets.

### ISSUE THREAD

**Issue by FengXinwen-news** [raghavian/loTeNet_pytorch#4]
I'm sorry to bother you, but I have read your paper "Locally orderless tensor networks for classifying two- and three-dimensional medical images" about the verification of LoTeNet on Pcam. I would like to know the preprocessing process of Pcam dataset. If it is convenient for me, I would like to learn the code you wrote.

**Comment by raghavian** [comment]
Hi 
We used the preprocessed data from the Kaggle challenge page as mentioned in the paper:
https://www.kaggle.com/c/histopathologic-cancer-detection
